---
title: '2019 College Football Season '
author: "Will Brazgel, Nick Bice, Nick Camp, and Nathan Wu"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)
library(googlesheets4)
library(lubridate)     
library(openintro)
library(maps) 
library(ggmap)
library(sf)            
library(leaflet)       
library(ggthemes)     
library(plotly)        
library(gganimate)    
library(gifski)
library(patchwork)     
library(gt)
library(stringr)
library(janitor)
gs4_deauth()
theme_set(theme_minimal())
```

```{r}
CFB2019 <- read_csv("CFB2019.csv") %>% 
  clean_names() %>% 
  separate(team, into = c("team", "conference"), sep = "\\(|\\)") %>% 
  separate(win_loss, into = c("wins", "losses"), sep = "-", convert = TRUE) %>%
  mutate(win_pct = wins/games,
         forced_tpg = turnovers_gain/games)
```

## Introduction

This data provides information on team statistics for all of the 130 FBS level college football teams in the United States. There are 145 different team statistics that can be used. This information was collected from the [NCAA Statistics website](https://www.ncaa.com/stats/football/fbs).


## SEC

### Offense

```{r}
#scale_color_manual(values = c("Alabama" = "990000", "Arkansas" = "CC0000", "Auburn" = "000066", "Florida" = "FF8000", "Georgia" = "000000", "Kentucky" = "0000FF", "LSU" = "660066", "Mississippi St." = "404040", "Missouri" = "FFFF33", "Ole Miss" = "3399FF", "South Carolina" = "A0A0A0", "Tennessee" = "FFB266", "Texas A&M" = "330019", "Vanderbilt" = "666600"))

sec1 <- CFB2019 %>% 
  filter(conference == "SEC") %>%
  mutate(team = fct_reorder(team, win_pct)) %>% 
  ggplot(aes(x = win_pct, y = team, fill = team))+
  labs(title = "Winning Percentage",
       x = "", 
       y = "")+
  scale_fill_stata()+
  theme(legend.position = "none")+
  geom_col()

sec2 <- CFB2019 %>% 
  filter(conference == "SEC") %>% 
  ggplot(aes(x = rushing_yards_per_game, y = points_per_game, color = team)) +
  scale_color_stata()+
  labs(title = "Rush Yards and Points Scored Per Game
       (Hover over Points)",
       x = "Rush Yards",
       y = "Points Scored",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(sec2) %>% 
  config(displayModeBar = FALSE)

sec3 <- CFB2019 %>% 
  filter(conference == "SEC") %>% 
  ggplot(aes(x = pass_yards_per_game, y = points_per_game, color = team)) +
  scale_color_stata()+
  labs(title = "Pass Yards and Points Scored Per Game
       (Hover over Points)",
       x = "Pass Yards",
       y = "Points Scored",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(sec3) %>% 
  config(displayModeBar = FALSE)

sec4 <- CFB2019 %>%
  filter(conference == "SEC") %>%
  mutate(team = fct_reorder(team, points_per_game)) %>% 
  ggplot(aes(y = team, x = points_per_game, fill = team)) +
  labs(title = "Points Per Game",
       x = "",
       y = "")+
  theme(legend.position = "none")+
  scale_fill_stata()+
  geom_col()

(sec1 | sec4)
```

### Defense

```{r}
#scale_color_manual(values = c("Alabama" = "990000", "Arkansas" = "CC0000", "Auburn" = "000066", "Florida" = "FF8000", "Georgia" = "000000", "Kentucky" = "0000FF", "LSU" = "660066", "Mississippi St." = "404040", "Missouri" = "FFFF33", "Ole Miss" = "3399FF", "South Carolina" = "A0A0A0", "Tennessee" = "FFB266", "Texas A&M" = "330019", "Vanderbilt" = "666600"))

sec6 <- CFB2019 %>% 
  filter(conference == "SEC") %>%
  mutate(team = fct_reorder(team, win_pct)) %>% 
  ggplot(aes(x = win_pct, y = team, fill = team))+
  scale_fill_stata()+
  labs(title = "Winning Percentage", 
       x = "", 
       y = "")+
  theme(legend.position = "none")+
  geom_col()

sec7 <- CFB2019 %>% 
  filter(conference == "SEC") %>% 
  ggplot(aes(x = tackle_for_loss_per_game, y = avg_points_per_game_allowed, color = team)) +
  scale_color_stata()+
  labs(title = "Tackles for Loss and Points Allowed Per Game
       (Hover over Points)",
       x = "TFLs",
       y = "Points Allowed",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(sec7)%>% 
  config(displayModeBar = FALSE)

sec8 <- CFB2019 %>% 
  filter(conference == "SEC") %>% 
  ggplot(aes(x = forced_tpg, y = avg_points_per_game_allowed, color = team)) +
  scale_color_stata()+
  labs(title = "Forced Turnovers and PPG Allowed
       (Hover over Points)",
       x = "Forced Turnovers",
       y = "Points Allowed",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(sec8)%>% 
  config(displayModeBar = FALSE)

sec9 <- CFB2019 %>% 
  filter(conference == "SEC") %>%
  mutate(team = fct_rev(fct_reorder(team, avg_points_per_game_allowed))) %>% 
  ggplot(aes(y = team, x = avg_points_per_game_allowed, fill = team)) +
  scale_fill_stata()+
  labs(title = "Points Allowed Per Game",
       x = "",
       y = "")+
  theme(legend.position = "none")+
  geom_col()

(sec6 | sec9)
```


## ACC

### Offense

```{r}
acc1 <- CFB2019 %>% 
  filter(conference == "ACC") %>%
  mutate(team = fct_reorder(team, win_pct)) %>% 
  ggplot(aes(x = win_pct, y = team, fill = team))+
  labs(title = "Winning Percentage",
       x = "", 
       y = "")+
  scale_fill_stata()+
  theme(legend.position = "none")+
  geom_col()

acc2 <- CFB2019 %>% 
  filter(conference == "ACC") %>% 
  ggplot(aes(x = rushing_yards_per_game, y = points_per_game, color = team)) +
  scale_color_stata()+
  labs(title = "Rush Yards and Points Scored Per Game
       (Hover over Points)",
       x = "Rush Yards",
       y = "Points Scored",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(acc2) %>% 
  config(displayModeBar = FALSE)

acc3 <- CFB2019 %>% 
  filter(conference == "ACC") %>% 
  ggplot(aes(x = pass_yards_per_game, y = points_per_game, color = team)) +
  scale_color_stata()+
  labs(title = "Pass Yards and Points Scored Per Game
       (Hover over Points)",
       x = "Pass Yards",
       y = "Points Scored",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(acc3) %>% 
  config(displayModeBar = FALSE)

acc4 <- CFB2019 %>%
  filter(conference == "ACC") %>%
  mutate(team = fct_reorder(team, points_per_game)) %>% 
  ggplot(aes(y = team, x = points_per_game, fill = team)) +
  labs(title = "Points Per Game",
       x = "",
       y = "")+
  theme(legend.position = "none")+
  scale_fill_stata()+
  geom_col()

(acc1 | acc4)
```

### Defense

```{r}
acc5 <- CFB2019 %>% 
  filter(conference == "ACC") %>%
  mutate(team = fct_reorder(team, win_pct)) %>% 
  ggplot(aes(x = win_pct, y = team, fill = team))+
  scale_fill_stata()+
  labs(title = "Winning Percentage", 
       x = "", 
       y = "")+
  theme(legend.position = "none")+
  geom_col()

acc6 <- CFB2019 %>% 
  filter(conference == "ACC") %>% 
  ggplot(aes(x = tackle_for_loss_per_game, y = avg_points_per_game_allowed, color = team)) +
  scale_color_stata()+
  labs(title = "Tackles for Loss and Points Allowed Per Game
       (Hover over Points)",
       x = "TFLs",
       y = "Points Allowed",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(acc6)%>% 
  config(displayModeBar = FALSE)

acc7 <- CFB2019 %>% 
  filter(conference == "ACC") %>% 
  ggplot(aes(x = forced_tpg, y = avg_points_per_game_allowed, color = team)) +
  scale_color_stata()+
  labs(title = "Forced Turnovers and Points Allowed Per Game
       (Hover over Points)",
       x = "Forced Turnovers",
       y = "Points Allowed",
       color = "")+
  theme(legend.title = element_blank())+
  geom_point()

ggplotly(acc7)%>% 
  config(displayModeBar = FALSE)

acc8 <- CFB2019 %>% 
  filter(conference == "ACC") %>%
  mutate(team = fct_rev(fct_reorder(team, avg_points_per_game_allowed))) %>% 
  ggplot(aes(y = team, x = avg_points_per_game_allowed, fill = team)) +
  scale_fill_stata()+
  labs(title = "Points Allowed Per Game",
       x = "",
       y = "")+
  theme(legend.position = "none")+
  geom_col()

(acc5 | acc8)
```

```{r}
CFB2019 %>%
  group_by(conference) %>% 
  summarize(avg_wins = mean(wins),
            avg_ppg_allowed = mean(avg_points_per_game_allowed),
            avg_ppg = mean(points_per_game))
```

